
CREATE TABLE assets
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    symbol      VARCHAR(255)                            NOT NULL,
    quantity    DECIMAL                                 NOT NULL,
    price       DECIMAL                                 NOT NULL,
    asset_value DECIMAL                                 NOT NULL,
    version     BIGINT,
    wallet_id   BIGINT,
    CONSTRAINT pk_assets PRIMARY KEY (id)
);

CREATE TABLE wallets
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_wallets PRIMARY KEY (id)
);

ALTER TABLE wallets
    ADD CONSTRAINT uc_wallets_email UNIQUE (email);

ALTER TABLE assets
    ADD CONSTRAINT FK_ASSETS_ON_WALLET FOREIGN KEY (wallet_id) REFERENCES wallets (id);

CREATE INDEX idx_assets_symbol ON assets (symbol);

CREATE INDEX idx_assets_wallet_id ON assets (wallet_id);
